spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: prod
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:~/mem;
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace