spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: prod
---
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: validate
  logging:
    level:
      org:
        springframework:
          jdbc:
            core: TRACE